# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Lint

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "main" ]

env:
  GO_VERSION: '1.22.4'

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
        
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: make install_dependencies


    - name: Run linter
      run: make lint
